export const currencyMap = {
    AED: {
  country: "United Arab Emirates",
  currency: "UAE Dirham",
  symbol: "د.إ",
  countryCode: "AE",
},
AFN: {
  country: "Afghanistan",
  currency: "Afghan Afghani",
  symbol: "؋",
  countryCode: "AF",
},
ALL: {
  country: "Albania",
  currency: "Albanian Lek",
  symbol: "L",
  countryCode: "AL",
},
AMD: {
  country: "Armenia",
  currency: "Armenian Dram",
  symbol: "֏",
  countryCode: "AM",
},
ANG: {
  country: "Curaçao & Sint Maarten",
  currency: "Netherlands Antillean Guilder",
  symbol: "ƒ",
  countryCode: "CW",
},
AOA: {
  country: "Angola",
  currency: "Angolan Kwanza",
  symbol: "Kz",
  countryCode: "AO",
},
ARS: {
  country: "Argentina",
  currency: "Argentine Peso",
  symbol: "$",
  countryCode: "AR",
},
AUD: {
  country: "Australia",
  currency: "Australian Dollar",
  symbol: "$",
  countryCode: "AU",
},
AWG: {
  country: "Aruba",
  currency: "Aruban Florin",
  symbol: "ƒ",
  countryCode: "AW",
},
AZN: {
  country: "Azerbaijan",
  currency: "Azerbaijani Manat",
  symbol: "₼",
  countryCode: "AZ",
},

BAM: {
  country: "Bosnia & Herzegovina",
  currency: "Convertible Mark",
  symbol: "KM",
  countryCode: "BA",
},
BBD: {
  country: "Barbados",
  currency: "Barbadian Dollar",
  symbol: "$",
  countryCode: "BB",
},
BDT: {
  country: "Bangladesh",
  currency: "Bangladeshi Taka",
  symbol: "৳",
  countryCode: "BD",
},
BGN: {
  country: "Bulgaria",
  currency: "Bulgarian Lev",
  symbol: "лв",
  countryCode: "BG",
},
BHD: {
  country: "Bahrain",
  currency: "Bahraini Dinar",
  symbol: ".د.ب",
  countryCode: "BH",
},
BIF: {
  country: "Burundi",
  currency: "Burundian Franc",
  symbol: "FBu",
  countryCode: "BI",
},
BMD: {
  country: "Bermuda",
  currency: "Bermudian Dollar",
  symbol: "$",
  countryCode: "BM",
},
BND: {
  country: "Brunei",
  currency: "Brunei Dollar",
  symbol: "$",
  countryCode: "BN",
},
BOB: {
  country: "Bolivia",
  currency: "Boliviano",
  symbol: "Bs.",
  countryCode: "BO",
},
BRL: {
  country: "Brazil",
  currency: "Brazilian Real",
  symbol: "R$",
  countryCode: "BR",
},
BSD: {
  country: "Bahamas",
  currency: "Bahamian Dollar",
  symbol: "$",
  countryCode: "BS",
},
BTN: {
  country: "Bhutan",
  currency: "Bhutanese Ngultrum",
  symbol: "Nu.",
  countryCode: "BT",
},
BWP: {
  country: "Botswana",
  currency: "Botswana Pula",
  symbol: "P",
  countryCode: "BW",
},
BYN: {
  country: "Belarus",
  currency: "Belarusian Ruble",
  symbol: "Br",
  countryCode: "BY",
},
BZD: {
  country: "Belize",
  currency: "Belize Dollar",
  symbol: "BZ$",
  countryCode: "BZ",
},
CAD: {
  country: "Canada",
  currency: "Canadian Dollar",
  symbol: "C$",
  countryCode: "CA",
},
CDF: {
  country: "Democratic Republic of the Congo",
  currency: "Congolese Franc",
  symbol: "FC",
  countryCode: "CD",
},
CHF: {
  country: "Switzerland",
  currency: "Swiss Franc",
  symbol: "CHF",
  countryCode: "CH",
},
CLP: {
  country: "Chile",
  currency: "Chilean Peso",
  symbol: "$",
  countryCode: "CL",
},
CNY: {
  country: "China",
  currency: "Chinese Yuan",
  symbol: "¥",
  countryCode: "CN",
},
COP: {
  country: "Colombia",
  currency: "Colombian Peso",
  symbol: "$",
  countryCode: "CO",
},
CRC: {
  country: "Costa Rica",
  currency: "Costa Rican Colón",
  symbol: "₡",
  countryCode: "CR",
},
CUP: {
  country: "Cuba",
  currency: "Cuban Peso",
  symbol: "₱",
  countryCode: "CU",
},
CVE: {
  country: "Cabo Verde",
  currency: "Cape Verdean Escudo",
  symbol: "$",
  countryCode: "CV",
},
CZK: {
  country: "Czechia",
  currency: "Czech Koruna",
  symbol: "Kč",
  countryCode: "CZ",
},

DJF: {
  country: "Djibouti",
  currency: "Djiboutian Franc",
  symbol: "Fdj",
  countryCode: "DJ",
},
DKK: {
  country: "Denmark",
  currency: "Danish Krone",
  symbol: "kr",
  countryCode: "DK",
},
DOP: {
  country: "Dominican Republic",
  currency: "Dominican Peso",
  symbol: "RD$",
  countryCode: "DO",
},
DZD: {
  country: "Algeria",
  currency: "Algerian Dinar",
  symbol: "دج",
  countryCode: "DZ",
},

EGP: {
  country: "Egypt",
  currency: "Egyptian Pound",
  symbol: "£",
  countryCode: "EG",
},
ERN: {
  country: "Eritrea",
  currency: "Eritrean Nakfa",
  symbol: "Nfk",
  countryCode: "ER",
},
ETB: {
  country: "Ethiopia",
  currency: "Ethiopian Birr",
  symbol: "Br",
  countryCode: "ET",
},
EUR: {
  country: "European Union",
  currency: "Euro",
  symbol: "€",
  countryCode: "EU",
},

FJD: {
  country: "Fiji",
  currency: "Fijian Dollar",
  symbol: "FJ$",
  countryCode: "FJ",
},
FKP: {
  country: "Falkland Islands",
  currency: "Falkland Islands Pound",
  symbol: "£",
  countryCode: "FK",
},


    GEL: {
  country: "Georgia",
  currency: "Georgian Lari",
  symbol: "₾",
  countryCode: "GE",
},
GGP: {
  country: "Guernsey",
  currency: "Guernsey Pound",
  symbol: "£",
  countryCode: "GG",
},
GHS: {
  country: "Ghana",
  currency: "Ghanaian Cedi",
  symbol: "₵",
  countryCode: "GH",
},
GIP: {
  country: "Gibraltar",
  currency: "Gibraltar Pound",
  symbol: "£",
  countryCode: "GI",
},
GMD: {
  country: "Gambia",
  currency: "Gambian Dalasi",
  symbol: "D",
  countryCode: "GM",
},
GNF: {
  country: "Guinea",
  currency: "Guinean Franc",
  symbol: "FG",
  countryCode: "GN",
},
GTQ: {
  country: "Guatemala",
  currency: "Guatemalan Quetzal",
  symbol: "Q",
  countryCode: "GT",
},
GYD: {
  country: "Guyana",
  currency: "Guyanese Dollar",
  symbol: "G$",
  countryCode: "GY",
},

HKD: {
  country: "Hong Kong",
  currency: "Hong Kong Dollar",
  symbol: "HK$",
  countryCode: "HK",
},
HNL: {
  country: "Honduras",
  currency: "Honduran Lempira",
  symbol: "L",
  countryCode: "HN",
},
HTG: {
  country: "Haiti",
  currency: "Haitian Gourde",
  symbol: "G",
  countryCode: "HT",
},
HUF: {
  country: "Hungary",
  currency: "Hungarian Forint",
  symbol: "Ft",
  countryCode: "HU",
},

    IDR: {
  country: "Indonesia",
  currency: "Indonesian Rupiah",
  symbol: "Rp",
  countryCode: "ID",
},
ILS: {
  country: "Israel",
  currency: "Israeli New Shekel",
  symbol: "₪",
  countryCode: "IL",
},
IMP: {
  country: "Isle of Man",
  currency: "Manx Pound",
  symbol: "£",
  countryCode: "IM",
},
INR: {
  country: "India",
  currency: "Indian Rupee",
  symbol: "₹",
  countryCode: "IN",
},
IQD: {
  country: "Iraq",
  currency: "Iraqi Dinar",
  symbol: "ع.د",
  countryCode: "IQ",
},
IRR: {
  country: "Iran",
  currency: "Iranian Rial",
  symbol: "﷼",
  countryCode: "IR",
},
ISK: {
  country: "Iceland",
  currency: "Icelandic Króna",
  symbol: "kr",
  countryCode: "IS",
},

JEP: {
  country: "Jersey",
  currency: "Jersey Pound",
  symbol: "£",
  countryCode: "JE",
},
JMD: {
  country: "Jamaica",
  currency: "Jamaican Dollar",
  symbol: "J$",
  countryCode: "JM",
},
JOD: {
  country: "Jordan",
  currency: "Jordanian Dinar",
  symbol: "JD",
  countryCode: "JO",
},
JPY: {
  country: "Japan",
  currency: "Japanese Yen",
  symbol: "¥",
  countryCode: "JP",
},

LAK: {
  country: "Laos",
  currency: "Lao Kip",
  symbol: "₭",
  countryCode: "LA",
},
LBP: {
  country: "Lebanon",
  currency: "Lebanese Pound",
  symbol: "ل.ل",
  countryCode: "LB",
},
LKR: {
  country: "Sri Lanka",
  currency: "Sri Lankan Rupee",
  symbol: "Rs",
  countryCode: "LK",
},
LRD: {
  country: "Liberia",
  currency: "Liberian Dollar",
  symbol: "L$",
  countryCode: "LR",
},
LSL: {
  country: "Lesotho",
  currency: "Lesotho Loti",
  symbol: "L",
  countryCode: "LS",
},
LYD: {
  country: "Libya",
  currency: "Libyan Dinar",
  symbol: "ل.د",
  countryCode: "LY",
},


    KES: {
  country: "Kenya",
  currency: "Kenyan Shilling",
  symbol: "KSh",
  countryCode: "KE",
},
KGS: {
  country: "Kyrgyzstan",
  currency: "Kyrgyzstani Som",
  symbol: "сом",
  countryCode: "KG",
},
KHR: {
  country: "Cambodia",
  currency: "Cambodian Riel",
  symbol: "៛",
  countryCode: "KH",
},
KMF: {
  country: "Comoros",
  currency: "Comorian Franc",
  symbol: "CF",
  countryCode: "KM",
},
KRW: {
  country: "South Korea",
  currency: "South Korean Won",
  symbol: "₩",
  countryCode: "KR",
},
KWD: {
  country: "Kuwait",
  currency: "Kuwaiti Dinar",
  symbol: "KD",
  countryCode: "KW",
},
KYD: {
  country: "Cayman Islands",
  currency: "Cayman Islands Dollar",
  symbol: "CI$",
  countryCode: "KY",
},
KZT: {
  country: "Kazakhstan",
  currency: "Kazakhstani Tenge",
  symbol: "₸",
  countryCode: "KZ",
},

MAD: {
  country: "Morocco",
  currency: "Moroccan Dirham",
  symbol: "MAD",
  countryCode: "MA",
},
MDL: {
  country: "Moldova",
  currency: "Moldovan Leu",
  symbol: "L",
  countryCode: "MD",
},
MGA: {
  country: "Madagascar",
  currency: "Malagasy Ariary",
  symbol: "Ar",
  countryCode: "MG",
},
MKD: {
  country: "North Macedonia",
  currency: "Macedonian Denar",
  symbol: "ден",
  countryCode: "MK",
},
MMK: {
  country: "Myanmar",
  currency: "Myanmar Kyat",
  symbol: "Ks",
  countryCode: "MM",
},
MNT: {
  country: "Mongolia",
  currency: "Mongolian Tögrög",
  symbol: "₮",
  countryCode: "MN",
},
MOP: {
  country: "Macau",
  currency: "Macanese Pataca",
  symbol: "MOP$",
  countryCode: "MO",
},
MRU: {
  country: "Mauritania",
  currency: "Mauritanian Ouguiya",
  symbol: "UM",
  countryCode: "MR",
},
MUR: {
  country: "Mauritius",
  currency: "Mauritian Rupee",
  symbol: "₨",
  countryCode: "MU",
},
MVR: {
  country: "Maldives",
  currency: "Maldivian Rufiyaa",
  symbol: "Rf",
  countryCode: "MV",
},
MWK: {
  country: "Malawi",
  currency: "Malawian Kwacha",
  symbol: "MK",
  countryCode: "MW",
},
MXN: {
  country: "Mexico",
  currency: "Mexican Peso",
  symbol: "MX$",
  countryCode: "MX",
},
MYR: {
  country: "Malaysia",
  currency: "Malaysian Ringgit",
  symbol: "RM",
  countryCode: "MY",
},
MZN: {
  country: "Mozambique",
  currency: "Mozambican Metical",
  symbol: "MT",
  countryCode: "MZ",
},



    NAD: {
  country: "Namibia",
  currency: "Namibian Dollar",
  symbol: "N$",
  countryCode: "NA",
},
NGN: {
  country: "Nigeria",
  currency: "Nigerian Naira",
  symbol: "₦",
  countryCode: "NG",
},
NIO: {
  country: "Nicaragua",
  currency: "Nicaraguan Córdoba",
  symbol: "C$",
  countryCode: "NI",
},
NOK: {
  country: "Norway",
  currency: "Norwegian Krone",
  symbol: "kr",
  countryCode: "NO",
},
NPR: {
  country: "Nepal",
  currency: "Nepalese Rupee",
  symbol: "₨",
  countryCode: "NP",
},
NZD: {
  country: "New Zealand",
  currency: "New Zealand Dollar",
  symbol: "NZ$",
  countryCode: "NZ",
},

OMR: {
  country: "Oman",
  currency: "Omani Rial",
  symbol: "﷼",
  countryCode: "OM",
},

PAB: {
  country: "Panama",
  currency: "Panamanian Balboa",
  symbol: "B/.",
  countryCode: "PA",
},
PEN: {
  country: "Peru",
  currency: "Peruvian Sol",
  symbol: "S/",
  countryCode: "PE",
},
PGK: {
  country: "Papua New Guinea",
  currency: "Papua New Guinean Kina",
  symbol: "K",
  countryCode: "PG",
},
PHP: {
  country: "Philippines",
  currency: "Philippine Peso",
  symbol: "₱",
  countryCode: "PH",
},
PKR: {
  country: "Pakistan",
  currency: "Pakistani Rupee",
  symbol: "₨",
  countryCode: "PK",
},
PLN: {
  country: "Poland",
  currency: "Polish Złoty",
  symbol: "zł",
  countryCode: "PL",
},
PYG: {
  country: "Paraguay",
  currency: "Paraguayan Guaraní",
  symbol: "₲",
  countryCode: "PY",
},

QAR: {
  country: "Qatar",
  currency: "Qatari Riyal",
  symbol: "﷼",
  countryCode: "QA",
},
RON: {
  country: "Romania",
  currency: "Romanian Leu",
  symbol: "lei",
  countryCode: "RO",
},
RSD: {
  country: "Serbia",
  currency: "Serbian Dinar",
  symbol: "дин.",
  countryCode: "RS",
},
RUB: {
  country: "Russia",
  currency: "Russian Ruble",
  symbol: "₽",
  countryCode: "RU",
},
RWF: {
  country: "Rwanda",
  currency: "Rwandan Franc",
  symbol: "RF",
  countryCode: "RW",
},

SAR: {
  country: "Saudi Arabia",
  currency: "Saudi Riyal",
  symbol: "﷼",
  countryCode: "SA",
},
SBD: {
  country: "Solomon Islands",
  currency: "Solomon Islands Dollar",
  symbol: "SI$",
  countryCode: "SB",
},
SCR: {
  country: "Seychelles",
  currency: "Seychellois Rupee",
  symbol: "₨",
  countryCode: "SC",
},
SDG: {
  country: "Sudan",
  currency: "Sudanese Pound",
  symbol: "SDG",
  countryCode: "SD",
},
SEK: {
  country: "Sweden",
  currency: "Swedish Krona",
  symbol: "kr",
  countryCode: "SE",
},
SGD: {
  country: "Singapore",
  currency: "Singapore Dollar",
  symbol: "S$",
  countryCode: "SG",
},
SHP: {
  country: "Saint Helena",
  currency: "Saint Helena Pound",
  symbol: "£",
  countryCode: "SH",
},
SLE: {
  country: "Sierra Leone",
  currency: "Sierra Leone Leone",
  symbol: "Le",
  countryCode: "SL",
},
SOS: {
  country: "Somalia",
  currency: "Somali Shilling",
  symbol: "Sh",
  countryCode: "SO",
},
SRD: {
  country: "Suriname",
  currency: "Surinamese Dollar",
  symbol: "$",
  countryCode: "SR",
},
SSP: {
  country: "South Sudan",
  currency: "South Sudanese Pound",
  symbol: "£",
  countryCode: "SS",
},
STN: {
  country: "São Tomé & Príncipe",
  currency: "São Tomé and Príncipe Dobra",
  symbol: "Db",
  countryCode: "ST",
},
SYP: {
  country: "Syria",
  currency: "Syrian Pound",
  symbol: "£",
  countryCode: "SY",
},
SZL: {
  country: "Eswatini",
  currency: "Swazi Lilangeni",
  symbol: "E",
  countryCode: "SZ",
},
THB: {
  country: "Thailand",
  currency: "Thai Baht",
  symbol: "฿",
  countryCode: "TH",
},
TJS: {
  country: "Tajikistan",
  currency: "Tajikistani Somoni",
  symbol: "ЅМ",
  countryCode: "TJ",
},
TMT: {
  country: "Turkmenistan",
  currency: "Turkmenistani Manat",
  symbol: "m",
  countryCode: "TM",
},
TND: {
  country: "Tunisia",
  currency: "Tunisian Dinar",
  symbol: "د.ت",
  countryCode: "TN",
},
TOP: {
  country: "Tonga",
  currency: "Tongan Paʻanga",
  symbol: "T$",
  countryCode: "TO",
},
TRY: {
  country: "Turkey",
  currency: "Turkish Lira",
  symbol: "₺",
  countryCode: "TR",
},
TTD: {
  country: "Trinidad & Tobago",
  currency: "Trinidad and Tobago Dollar",
  symbol: "TT$",
  countryCode: "TT",
},
TWD: {
  country: "Taiwan",
  currency: "New Taiwan Dollar",
  symbol: "NT$",
  countryCode: "TW",
},
TZS: {
  country: "Tanzania",
  currency: "Tanzanian Shilling",
  symbol: "TSh",
  countryCode: "TZ",
},

UAH: {
  country: "Ukraine",
  currency: "Ukrainian Hryvnia",
  symbol: "₴",
  countryCode: "UA",
},
UGX: {
  country: "Uganda",
  currency: "Ugandan Shilling",
  symbol: "USh",
  countryCode: "UG",
},
USD: {
  country: "United States",
  currency: "US Dollar",
  symbol: "$",
  countryCode: "US",
},
UYU: {
  country: "Uruguay",
  currency: "Uruguayan Peso",
  symbol: "$U",
  countryCode: "UY",
},
UZS: {
  country: "Uzbekistan",
  currency: "Uzbekistani Som",
  symbol: "so'm",
  countryCode: "UZ",
},
VES: {
  country: "Venezuela",
  currency: "Venezuelan Bolívar",
  symbol: "Bs.",
  countryCode: "VE",
},
VND: {
  country: "Vietnam",
  currency: "Vietnamese Đồng",
  symbol: "₫",
  countryCode: "VN",
},
VUV: {
  country: "Vanuatu",
  currency: "Vanuatu Vatu",
  symbol: "VT",
  countryCode: "VU",
},

WST: {
  country: "Samoa",
  currency: "Samoan Tālā",
  symbol: "WS$",
  countryCode: "WS",
},

XAF: {
  country: "Central African CFA",
  currency: "Central African CFA Franc",
  symbol: "FCFA",
  countryCode: "CM",
},
XCD: {
  country: "East Caribbean",
  currency: "East Caribbean Dollar",
  symbol: "EC$",
  countryCode: "AG",
},
XCG: {
  country: "Curaçao & Sint Maarten",
  currency: "Caribbean Guilder",
  symbol: "Cg",
  countryCode: "CW",
},
XDR: {
  country: "International Monetary Fund",
  currency: "Special Drawing Rights",
  symbol: "SDR",
  countryCode: "UN",
},
XOF: {
  country: "West African CFA",
  currency: "West African CFA Franc",
  symbol: "CFA",
  countryCode: "SN",
},
XPF: {
  country: "French Pacific Territories",
  currency: "CFP Franc",
  symbol: "₣",
  countryCode: "PF",
},

YER: {
  country: "Yemen",
  currency: "Yemeni Rial",
  symbol: "﷼",
  countryCode: "YE",
},

ZAR: {
  country: "South Africa",
  currency: "South African Rand",
  symbol: "R",
  countryCode: "ZA",
},
ZMW: {
  country: "Zambia",
  currency: "Zambian Kwacha",
  symbol: "ZK",
  countryCode: "ZM",
},
ZWL: {
  country: "Zimbabwe",
  currency: "Zimbabwe Gold",
  symbol: "ZiG",
  countryCode: "ZW",
},

};

export const getCurrencyDetails = (code) => {
  return currencyMap[code] || { country: "Unknown", countryCode: "US" };
};